"""empty message

Revision ID: 999cf414bc2a
Revises: d4cc7cd3609f
Create Date: 2022-08-12 13:07:53.370205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999cf414bc2a'
down_revision = 'd4cc7cd3609f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('venue_looking', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_desc', sa.String(length=300), nullable=True))
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('Artist', 'seeking_desc')
    op.drop_column('Artist', 'venue_looking')
    op.drop_column('Artist', 'website_link')
    op.drop_table('Show')
    # ### end Alembic commands ###
