"""empty message

Revision ID: d4cc7cd3609f
Revises: c1d4f45f4965
Create Date: 2022-08-09 08:27:43.338890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cc7cd3609f'
down_revision = 'c1d4f45f4965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('talent_looking', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_desc', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_desc')
    op.drop_column('Venue', 'talent_looking')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
